import {State} from 'types/state';
// import {TABS_TYPES} from './tabs';

const DEFAULT_STATE: State = {
  status: {
    loading: false,
    stateLoaded: false,
  },
  sidebar: {
    isCollapse: false,
    collapseClick: false,
    collapseHover: false,
    onToggleCollapse: () => {},
    onHoverEnter: () => {},
    onHoverLeave: () => {},
  },
  modal: {
    showModal: () => {},
    hideModal: () => {},
    store: {},
  },
  tabs: {
    tabsType: 'Dashboard',
  },
  notification: {
    show: false,
    notificationType: 'info',
    delayed: true,
    message: '',
  },
  user: {
    accountType: '',
    operatorId: '',
    personalDetails: {
      email: '',
      phone: '',
      name: '',
      description: '',
    },
    fleets: {
      _id: '',
      isIndividual: false,
      name: '',
      VAT: '',
      permitHolderName: '',
      permitNumber: '',
      permitHolderAddress: '',
      termsAndConditions: '',
      permitHolderContactDetails: '',
      permitHolderEmail: '',
      permitHolderLogo: '',
      prefix: '',
      ownerEmail: '',
      membersEmails: [],
      docketNumber: '',
      individualDocketNumber: '',
      createdAt: '',
      allowedWaste: {
        label: '',
        value: '',
      },
    },
    subscription: {
      _id: '',
      plan: '',
      oldPlan: '',
      status: '',
      trialEndsAt: '',
      startAt: '',
      endsAt: '',
      stripeSubscriptionId: '',
      stripeCustomerId: '',
      stripeProductId: '',
      stripePriceId: '',
      createdAt: '',
      updatedAt: '',
      maxLimit: '',
      limit: '',
    },
    selectedFleet: {
      _id: '',
      isIndividual: false,
      name: '',
      VAT: '',
      permitHolderName: '',
      permitNumber: '',
      permitHolderAddress: '',
      termsAndConditions: '',
      permitHolderContactDetails: '',
      permitHolderEmail: '',
      permitHolderLogo: '',
      prefix: '',
      ownerEmail: '',
      membersEmails: [],
      docketNumber: '',
      individualDocketNumber: '',
      createdAt: '',
      allowedWaste: {
        label: '',
        value: '',
      },
    },
    createdAt: '',
  },
};
export default DEFAULT_STATE;
